name: rounded_loading_button
description: A simple implementation of an animated loading button widget for Flutter
version: 2.1.0
homepage: https://github.com/chrisedg87/flutter_rounded_loading_button

environment:
   sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.1

flutter:
